apiVersion: v1
kind: Service
metadata:
  name: bind9-service
  namespace: dns-ha

spec:
  type: NodePort

  selector:
    app: bind9

  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
      nodePort: 30053

    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
      nodePort: 30053
