options {
    directory "/var/cache/bind";

    recursion no;

    allow-query {
        any;
    };
};

zone "trabajofinal.local" IN {
    type master;
    file "/etc/bind/db.trabajofinal.local";
};
